<?php

namespace cobe\GruposBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EstadoGrupoPersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoGrupoPersonaRepository extends EntityRepository
{
}
