<?php

namespace cobe\GruposBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GrupoPersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoPersonaRepository extends EntityRepository
{
}
