<?php

namespace cobe\GruposBundle\Repository;

use cobe\CommonBundle\Repository\ObjectRepository;

/**
 * VotacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VotacionRepository extends ObjectRepository
{
}
