<?php

namespace cobe\PaginasBundle\Repository;

use cobe\CommonBundle\Repository\ObjectRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends ObjectRepository
{
}
