<?php

namespace cobe\PaginasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlantillaPublicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantillaPublicacionRepository extends EntityRepository
{
}
