<?php

namespace cobe\PaginasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlantillaMensajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantillaMensajeRepository extends EntityRepository
{
}
