<?php

namespace cobe\PlantillasBundle\Repository;

use cobe\CommonBundle\Repository\ObjectRepository;

/**
 * PlantillaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantillaRepository extends ObjectRepository
{
}
