<?php

namespace cobe\PaginasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlantillaEmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantillaEmpresaRepository extends EntityRepository
{
}
