<?php

namespace cobe\PaginasBundle\Repository;

use cobe\CommonBundle\Repository\ObjectRepository;

/**
 * PublicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicacionRepository extends ObjectRepository
{
    public function getAllObj(){
        return $this->createQueryBuilder('o')->getQuery()->getResult();
    }
}
