<?php

namespace cobe\CommonBundle\Repository;

use cobe\CommonBundle\Repository\ObjectRepository;

/**
 * PaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaisRepository extends ObjectRepository{

}
