<?php

namespace cobe\CommonBundle\Repository;

use cobe\CommonBundle\Repository\ObjectRepository;

/**
 * TipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoRepository extends ObjectRepository
{
}
