<?php

namespace cobe\CurriculosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AptitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AptitudRepository extends EntityRepository
{
}
