<?php

namespace cobe\CurriculosBundle\Repository;

use cobe\CommonBundle\Repository\ObjectRepository;

/**
 * CentroEstudioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentroEstudioRepository extends ObjectRepository
{
}
