<?php

namespace cobe\CurriculosBundle\Repository;

use cobe\CommonBundle\Repository\ObjectRepository;

/**
 * EstudioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudioRepository extends ObjectRepository
{
}
