<?php

namespace cobe\CurriculosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IdiomaPersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdiomaPersonaRepository extends EntityRepository
{
}
