<?php

namespace cobe\CurriculosBundle\Repository;

use cobe\CommonBundle\Repository\ObjectRepository;

/**
 * RecomendacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecomendacionRepository extends ObjectRepository
{
}
