<?php

namespace cobe\MensajesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DestinatarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinatarioRepository extends EntityRepository
{
}
