<?php

namespace cobe\MensajesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EstadoDestinatarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoDestinatarioRepository extends EntityRepository
{
}
