<?php

namespace cobe\MensajesBundle\Repository;

use cobe\CommonBundle\Repository\ObjectRepository;

/**
 * MensajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensajeRepository extends ObjectRepository
{
}
