<?php

namespace cobe\UsuariosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EstadoUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoUsuarioRepository extends EntityRepository
{
}
