<?php

namespace cobe\UsuariosBundle\Repository;

use cobe\CommonBundle\Repository\ObjectRepository;

/**
 * EstudianteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudianteRepository extends ObjectRepository
{
}
