<?php

namespace cobe\UsuariosBundle\Repository;

use cobe\CommonBundle\Repository\ObjectRepository;
use cobe\UsuariosBundle\Entity\Usuario;
use Symfony\Component\Config\Definition\Exception\Exception;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends ObjectRepository
{
    public function validaUsuario($clave, $email = '', $nombre = ''){
        $qb = $this->createQueryBuilder('u');
        $usr = new Usuario();
        $clave = $usr->setClave($clave)->getClave();
        $qb
            ->andWhere($qb->expr()->orX($qb->expr()->like('u.email',$qb->expr()->literal($email)),$qb->expr()->like('u.nombre',$qb->expr()->literal($nombre))))
            ->andWhere($qb->expr()->like('u.clave',$qb->expr()->literal($clave)))
            ->setMaxResults(1)
        ;
        //$rta = $qb->getQuery()->execute();
        $rta = $qb->getQuery()->getResult();
        if(isset($rta[0])){
            $rta = $rta[0];
        }else{
            $rta = null;
        }
        return $rta;
    }
}
