<?php

namespace cobe\OfertasLaboralesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OfertaLaboralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfertaLaboralRepository extends EntityRepository
{
}
