<?php

namespace cobe\OfertasLaboralesBundle\Repository;

use cobe\CommonBundle\Repository\ObjectRepository;

/**
 * OfertaLaboralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfertaLaboralRepository extends ObjectRepository
{
}
