<?php

namespace cobe\EstadisticasBundle\Repository;

use cobe\CommonBundle\Repository\ObjectRepository;

/**
 * CaracteristicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaracteristicaRepository extends ObjectRepository
{
}
