<?php

namespace cobe\EstadisticasBundle\Repository;

use cobe\CommonBundle\Repository\ObjectRepository;

/**
 * EstadisticaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadisticaRepository extends ObjectRepository
{
}
