<?php

namespace cobe\ColeccionesBundle\Repository;

use cobe\CommonBundle\Repository\ObjectRepository;

/**
 * ArchivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivoRepository extends ObjectRepository{

}
